### ISSUE TITLE
404 on entries/import.xml ?

### ISSUE THREAD

**Issue by davestewart** [cheerful/freckle-apidocs#1]
Not sure if this is an issue, or me just getting to know the system, but when I call the entries page:

http://davestewart.letsfreckle.com/api/entries/import.xml?token=<mytoken>

I get a 404 error. A call to api/entries works just fine, so I know I am calling the URL correctly.

Perhaps I'm not passing the data correctly? Should the XML be in a key=value pair? If so, I'm not sure what the key name should be from the docs.

Cheers,
Dave

**Comment by davestewart** [comment]
Sorry - the token got scrubbed as I put it in angle-brackets, but that's where I'm putting mt token.

**Comment by kommen** [comment]
The import action is POST only. If you just request the import.xml with a browser, it will do a GET request and thus it won't be successful.

See the "Bulk Import" section in entries.mkdn for an example on how to issue a POST request.

**Comment by davestewart** [comment]
I'm using PHP cURL lib actually, and it is being posted. 

perhaps the problem may be that I'm not passing the data through properly? I have it in a file as per your example, but I'm not sure what key to use for the XML data, so I tried a variety of key names... but the 404 stopped me in my tracks.

(Also - it might be worth changing the status code to something more useful... or include an error message?)

**Comment by kommen** [comment]
The 404 does indeed mean that the method/http verb combination was not found. If your request data wasn't valid you get a 500 (I just verified that).

You don't have to use a key for the XML data, as the POST body should be the XML only. I'm not familiar with PHP's cURL, but this looks promising to me:
http://stackoverflow.com/questions/238784/php4-send-xml-over-https-post-via-curl

**Comment by davestewart** [comment]
I cannot for the life of me get this to work, and I think my source code is pretty straightforward.

My latest results on posting the data directly in the POST using cURL is an HTML page:

We're sorry, but something went wrong. We've been notified of this problem and will fix it shortly.

Is there somewhere other than here I can get support? I feel bad clogging up your issues page with something that may not even be an issue.

**Comment by kommen** [comment]
Please drop me an email to support@letsfreckle.com and I'll have a look at it.
