### ISSUE TITLE
Mark (project) deprecated fields clearly

### ISSUE THREAD

**Issue by mac-cain13** [cheerful/freckle-apidocs#11]
The /api/projects endpoint for example does give a "budget_minutes" and "budget" value for every project. I remember reading somewhere that one of there is deprecated, but I can't find any deprecation warning in the new and improved docs.

I think the deprecated values should be clearly marked as such, just like the entries are annotated in the API docs.

If there is no time to update the docs right now it would be nice to know what the right value is to use in the case of a project, "budget_minutes" or "budget"? And if there are more (undocumented) deprecated fields, if they are noted here it would be they are at least documented somewhere and it's way easier to create a pull request. :)

**Comment by madrobby** [comment]
I'll work on that! :)

**Comment by mac-cain13** [comment]
Great! :) A subtile API change of budget giving back 0 and budget_minutes being NULL (or the other way around) in combination with me being unsure which one to use crashed Pigment. That's why I tried to check which one was deprecated, but couldn't find anything.

Anyway, nice to know you're on it!

**Comment by madrobby** [comment]
Added to docs.
