### ISSUE TITLE
Docs mention nothing about how to "register an application"

### ISSUE THREAD

**Issue by JakeSidSmith** [cheerful/freckle-apidocs#22]
I'd like to create a web app that integrates with Freckle, using the v2 API with OAuth.

I understand that OAuth is "almost finished", but despite no mention that the web application flow is "not implemented" there doesn't appear to be any mention of how to obtain a `client_id` or `client_secret`.

The docs mention (http://developer.letsfreckle.com/v2/oauth/#web-application-flow)

> The client ID you received from Freckle when you registered your application.

But there is no link, and I haven't been able to find anywhere to register an application within Freckle.

How do I obtain these credentials, and should the docs be updated? Is this implemented yet?

**Comment by tcannonfodder** [comment]
Hey Jake!

Good find, sorry about the confusion here! I've just added a help doc that includes steps for registering an OAuth2 app: https://help.letsfreckle.com/article/122-registering-a-new-freckle-app

Please let me know if you have any other questions, or need help with anything else! And thanks for building an app that connects to Freckle, it's always super exciting when that happens 😄

**Comment by JakeSidSmith** [comment]
Thanks for the quick response. Those are basically the steps I tried to follow, but I see no "Register an app" link.

Could this be something to do with my permissions (as it's a company account)?

<img width="654" alt="screen shot 2018-07-03 at 12 11 07" src="https://user-images.githubusercontent.com/5850625/42216609-47e93a12-7eba-11e8-96a0-7c273d5e95de.png">

**Comment by JakeSidSmith** [comment]
If it's to do with my account type / permissions it'd probably be worth mentioning that.

**Comment by JakeSidSmith** [comment]
@tcannonfodder I signed up for the free trial yesterday, and I see that I now have these options. I think it'd be worth mentioning the account type / permissions that are required for this in the docs.

Also, is there a way to sign up for a developer account, or extended trial? I don't imagine many people would want to pay for an extra account when working on an integration, or risk changing their real data.
